List boqList = [
  {
    "snNo": "1",
    "specification": "A.1.DEMOLITION WORK",
    "unit": "Sqm",
    "totalQty": "5",
    "misc":"8",
    "ohm":"39.90",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "1122",
    "amount": "5610",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "A.1.DEMOLITION WORK: Dismantling/removal of existing brick / block wall, existing wall cladding / "
        "flooring, door frames and lintels at locations as indicated on the drawings to accommodate design "
        "changes and carting away all debris away from the site. No additional payment shall be payable for leads and lifts.",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "2",
    "specification": "B.1.CEMENT PLASTERING 19mm",
    "unit": "Sqm",
    "totalQty": "5",
    "misc":"8",
    "ohm":"11.80",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "1122",
    "amount": "5610",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "B.1.CIVIL & WETWORKS: CEMENT PLASTERING 19mm: Providing and applying Sand Cement Plaster "
        "1:6 over existing Walls / Columns / RCC Surfaces to line level and plumb to smooth finish ready "
        "to receive POP Punning / or cladding. Cost to include for hacking existing surface for proper bonding "
        "all complete inclusive of necessary scaffolding & curing. Plastering 12mm average thickness.",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "3",
    "specification": "B.2FLOOR TILE OF RECEPTION",
    "unit": "Sqm",
    "totalQty": "73",
    "misc":"8",
    "ohm":"6.05",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "2132",
    "amount": "155636",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "B.2FLOOR TILE OF RECEPTION: Providing & Laying Tile on Ňoor as per design & manufacturer's"
        "instruction. Cost includes, base mortar upto 40mm thk in ratio 1:5 (1 part of cement to 5 parts of"
        "sand) with appropriate level as per architects instruction, Laying tiles on a thin cement slurry paste &"
        "necessary protection aŌer laying. Tile joints to have 3mm wide spacer filled with epoxy grout of"
        "approved color by architects. Laying & fixing details as suggested by the manufacturer to be followed."
        "Cost includes of base wall / Ňoor protection to plumb / level. Vitrified tile; Basic rate of tile- Rs.950/-"
        "per sq.m + tax. Tile size: 600mm x 600mm. Note : Any change in basic cost shall be deducted or"
        "added.",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "4",
    "specification": "B.3.WALL TILE FOR PANTRY",
    "unit": "Sqm",
    "totalQty": "5",
    "misc":"18.73",
    "ohm":"6.05",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "2669",
    "amount": "13345",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "B.3.WALL TILE FOR PANTRY Backsplash: Providing & Laying Tile on wall as per design & manufacturer's"
        "instruction. Cost includes, base mortar upto 20mm thk in ratio 1:4 (1 part of cement to 4 parts of "
        "sand) with appropriate plumb and level. Tile joints to have 2mm wide spacer filled cementious joining"
        "compound of approved color by architects. Laying & fixing details as suggested by the manufacturer "
        "to be followed. Cost includes of base wall and Ňoor preparation to plumb level. Ceramic tile; Basic"
        "rate of tile- Rs.1500/- per sq.m + tax. Size - 100x200mm. All tile quantity to be cross checked by the"
        "vendor at site before executing. vitrified tiles",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "5",
    "specification": "B.6.ANTI TERMITE TREATMENT",
    "unit": "Sqm",
    "totalQty": "600",
    "misc":"8",
    "ohm":"19.50",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "69",
    "amount": "41400",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "B.6.ANTI TERMITE TREATMENT: Confirming to IS: 6313 (part-ii) 1981, providing pest control and anti"
        "termite treatment by appointing a specialised agency as per the specifications mentioned by the"
        "bureau of indian standards and agencies specifications (whichever is higher),for general, civil, "
    "plumbing, drainage, timber/carpentry works & gypsum related works, including a 10-years guarantee"
    "under suitable undertaking etc.complete as directed.(mode of measurement to be on carpet -area of "
    "Ňoor & not the area of surface treated).",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "6",
    "specification": "B.7.Leveling mortar",
    "unit": "Sqm",
    "totalQty": "10",
    "misc":"8",
    "ohm":"-31.30",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "411",
    "amount": "4110",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "B.7.Leveling mortar: Providing and laying 1:2 rich mix Plain cement leveling Mortar over existing"
        "screed 20mm thk. Cost to be inclusive of lead, liŌ, and curing",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "7",
    "specification": "B.8.Screed",
    "unit": "Sqm",
    "totalQty": "5",
    "misc":"8",
    "ohm":"17.60",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "825",
    "amount": "4125",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "B.8.Screed: Providing and laying 1:2:4 nominal mix Plain cement concrete screed ( 1 cement : 2 sand: "
        "4 stone aggregate 10mm and below sie) over raw slab areas in 60 mm average thickness to be "
        "finished with power troweller in proper level and slope etc. Rate shall include curing etc. complete.",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "8",
    "specification": "C.1.FIXED SINGLE GLAZED PARTITION SYSTEM",
    "unit": "Sqm",
    "totalQty": "39",
    "misc":"8",
    "ohm":"4.35",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "3901",
    "amount": "152139",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "C.1.PARTITION & PANELING: FIXED SINGLE GLAZED PARTITION SYSTEM: Supply and installation of "
        "Modular Aluminium single glazed partition (Slim line Series) having member size of 45 x 25 mm for"
        "10mm thick toughened glass, fixed with Modular channel at top and BoƩom mullion should snap on "
        "system, one vertical side to have glazing mullion head as per design and drawing. Supply & Fixing of"
        "glazing of 10mm thick toughened glass glazing fixed with All-round beading system aluminium "
        "member as per manufacturer specification. Cost to include, End cap all around the Aluminium"
        "member. Product to be certified by Manufacturer's Representative to Fix the Glass partition & glass"
    "door on the existing gyp partition necessary wooden framing to be inclusive in the cost. Glass to glass"
    "joints to have 'I' proĮle and glass to have aluminium profiles at 90 Deg joints - Height to be "
    "considered: 2400mm",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "9",
    "specification": "C.2.GYPSUM BOARD PARTITION - 100mm Thk",
    "unit": "Sqm",
    "totalQty": "232",
    "misc":"8",
    "ohm":"3",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "2136",
    "amount": "475552",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "C.2.GYPSUM BOARD PARTITION - 100mm Thk.(DoubleLayered): Providing and fixing gypsum board "
        "partitions using GI stud of sizes - 50 gypsteel ceiling & Floor channel,with Vertical 48mm Gypsteel stud "
        "and horizontal nogging channel to be provided as per manufacturer's specifications. cost includes "
        "Hardwood to be inserted at door opening to fix door frames, skirting etc. 12.5mm tappered edge "
        "gypsum board to fixed to the framework with dry wall screws, jointed and finished with required filler, "
        "paper tapefinsiher and primer suitable for gypsum plasterboards."
        "Cost of the partition to include for 50mm thk glass wool Insulation 48Kg/m2 density infill for the"
        "complete area of the partition. Installation of the glass wool shall be protected with Tissue covering"
        "taped to the frame or plastic sheet taped to the frame on one side. Cost of the partition shall be"
        "inclusive of necessary additional bracing of the frames at the slab level for stability with making "
    "necessary cutouts for electrical / data and other service outlets and also for passing through ducts"
    "cable trays and other service requirements. adding 12mm ply backing at TV or any shelf hanging "
    "areas.Cost to include applying fire and acoustical sealents at pheriphery of partitions & cut outs of "
    "services from both sides as per manufactures specifications. Make: Saint gobain Gyproc",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "10",
    "specification": "C.3.122mm Drywall",
    "unit": "Sqm",
    "totalQty": "22",
    "misc":"8",
    "ohm":"1.90",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "3448",
    "amount": "75856",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
  {
    "snNo": "",
    "specification" : "C.3.122mm Drywall : (Certified 2 Hrs Fire Rated – with 70mm C Stud @ 610mm c/c + Fireline Board + "
        "Habito Board both sides ) (Maximum Reachable Height <= 4600mm)"
        "122mm thick Gypsteel ULTRA® C Stud partition which includes inner layer of tapered edge 12.5mm"
        "thick Gyproc® Fireline (conforming to IS 2095 Part 1 : 2011/ EN520::2004, TYPE-F/ ASTM C1396, TYPE"
        "X) of size 1219x2438mm and outer layer of tapered edge 12.5mm thick Gyproc® Habito (conforming"
        "to EN 520: 2004, A1:2009, Type A,D,R,I) of size 1220x2440mm is screw Įxed to C-stud. 70x0.5mm "
        "Gypsteel ULTRA® C Stud placed at 610mm c/c in 72x0.5mm Gypsteel ULTRA® Ňoor and ceiling "
        "channel. Floor & Ceiling channel is anchored to the Ňoor & True ceiling using Gyproc® Rawl plug "
        "Ø8x45mm {Material-IS 513 CR1 grade, Zinc coating, Pull Out Load-7.5kN for M20 concrete "
        "grade} /Hilti X-GN20MX anchor fasteners at 600mm c/c in zigzag manner. 12.5mm Gyproc® Fireline "
        "board strip of 72 mm width is placed between ceiling channel and RCC ceiling slab to improve Įre"
        "performance of the system. A Gypsteel ULTRA® Noggin channel of 70x0.5mm width has to be "
        "provided at the horizontal joints of the two boards. Gyproc® boards to be screw fixed with Gyproc®"
        "drywall screws of 25mm & Gyproc® Habito Drywall screws of 35mm at minimum spacing of 600mm at"
        "Įre and acoustic sealant. Framework has to be done with Gypsteel ULTRA® {Material –IS513 CR1 "
        "Grade; Y/S-260Mpa Finish-Galvanized 120GSM as per IS277} from Ňoor up to soĸt. All other detailing"
        "and specifications to be followed as per approved drawing of Gyproc. For fire certification process, "
        "contractor/site in-charge should involve Saint Gobain Gyproc Technical Team prior to start of partition work.",
    "unit": "",
    "totalQty": "",
    "misc":"",
    "ohm":"",
    "remarks": "",
    "department": "",
    "packages": "",
    "network": "",
    "activity": "",
    "rate": "",
    "amount": "",
    "totalPerBoqQty": "",
    "profitMargin": "",
  },
];

List purchaseBudgetList = [
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "Course Aggregate",
    "materialQuantity": 51,
    "materialUnit": "CFT",
    "materialRate": 38.0,
    "materialAmount": 1920,
    "thickness": "6mm",
    "materialType": "",
    "excelData": {
      "snNo": "6",
      "specification": "B.7.Leveling mortar",
      "totalQty": 50,
      "amount": 1900,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "Course Aggregate",
    "materialQuantity": 51,
    "materialUnit": "CFT",
    "materialRate": 38.0,
    "materialAmount": 1920,
    "thickness": "6mm",
    "materialType": "",
    "excelData": {
      "snNo": "7",
      "specification": "B.8.Screed",
      "totalQty": 0.54,
      "amount": 20,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "Ramco",
    "materialModel": "Cement OPC",
    "materialQuantity": 35,
    "materialUnit": "Nos",
    "materialRate": 310.00,
    "materialAmount": 10738,
    "thickness": "50kg bags",
    "materialType": "Grade53",
    "excelData": {
      "snNo": "2",
      "specification": "B.1.CEMENT PLASTERING 19mm",
      "totalQty": 0.70,
      "amount": 217,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "Ramco",
    "materialModel": "Cement OPC",
    "materialQuantity": 35,
    "materialUnit": "Nos",
    "materialRate": 310.00,
    "materialAmount": 10738,
    "thickness": "50kg bags",
    "materialType": "Grade53",
    "excelData": {
      "snNo": "3",
      "specification": "B.2FLOOR TILE OF RECEPTION",
      "totalQty": 27.50,
      "amount": 8526,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "Ramco",
    "materialModel": "Cement OPC",
    "materialQuantity": 35,
    "materialUnit": "Nos",
    "materialRate": 310.00,
    "materialAmount": 10738,
    "thickness": "50kg bags",
    "materialType": "Grade53",
    "excelData": {
      "snNo": "4",
      "specification": "B.3.WALL TILE FOR PANTRY",
      "totalQty": 1.08,
      "amount": 334,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "Ramco",
    "materialModel": "Cement OPC",
    "materialQuantity": 35,
    "materialUnit": "Nos",
    "materialRate": 310.00,
    "materialAmount": 10738,
    "thickness": "50kg bags",
    "materialType": "Grade53",
    "excelData": {
      "snNo": "6",
      "specification": "B.7.Leveling mortar",
      "totalQty": 3.15,
      "amount": 978,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "Ramco",
    "materialModel": "Cement OPC",
    "materialQuantity": 35,
    "materialUnit": "Nos",
    "materialRate": 310.00,
    "materialAmount": 10738,
    "thickness": "50kg bags",
    "materialType": "Grade53",
    "excelData": {
      "snNo": "7",
      "specification": "B.8.Screed",
      "totalQty": 2.21,
      "amount": 684,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "Coarse Aggregate",
    "materialQuantity": 11,
    "materialUnit": "CFT",
    "materialRate": 0.01,
    "materialAmount": 0,
    "thickness": "Above 18mm",
    "materialType": "",
    "excelData": {
      "snNo": "7",
      "specification": "B.8.Screed",
      "totalQty": 10.82,
      "amount": 0,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "S/o; M sand",
    "materialQuantity": 357,
    "materialUnit": "CFT",
    "materialRate": 60.00,
    "materialAmount": 21398,
    "thickness": "",
    "materialType": "",
    "excelData": {
      "snNo": "3",
      "specification": "B.2FLOOR TILE OF RECEPTION",
      "totalQty": 314.32,
      "amount": 18859,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "S/o; M sand",
    "materialQuantity": 357,
    "materialUnit": "CFT",
    "materialRate": 60.00,
    "materialAmount": 21398,
    "thickness": "",
    "materialType": "",
    "excelData": {
      "snNo": "4",
      "specification": "B.3.WALL TILE FOR PANTRY",
      "totalQty": 4.65,
      "amount": 279,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "S/o; M sand",
    "materialQuantity": 357,
    "materialUnit": "CFT",
    "materialRate": 60.00,
    "materialAmount": 21398,
    "thickness": "",
    "materialType": "",
    "excelData": {
      "snNo": "6",
      "specification": "B.7.Leveling mortar",
      "totalQty": 16.15,
      "amount": 969,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "S/o; M sand",
    "materialQuantity": 357,
    "materialUnit": "CFT",
    "materialRate": 60.00,
    "materialAmount": 21398,
    "thickness": "",
    "materialType": "",
    "excelData": {
      "snNo": "7",
      "specification": "B.8.Screed",
      "totalQty": 21.53,
      "amount": 1292,
    }
  },
  {
    "materialDescription": "Civil Items",
    "materialMake": "NA",
    "materialModel": "S/o; M sand",
    "materialQuantity": 357,
    "materialUnit": "CFT",
    "materialRate": 60.00,
    "materialAmount": 21398,
    "thickness": "",
    "materialType": "",
    "excelData": {
      "snNo": "7",
      "specification": "B.8.Screed",
      "totalQty": 21.53,
      "amount": 1292,
    }
  },
  {
    "materialDescription": "Plywood & Timber",
    "materialMake": "Greenply",
    "materialModel": "S/o; MDF ",
    "materialQuantity": 196,
    "materialUnit": "SFT",
    "materialRate": 28.15,
    "materialAmount": 5405,
    "thickness": "8mm Thick",
    "materialType": "",
    "excelData": {
      "snNo": "8",
      "specification": "C.1.FIXED SINGLE GLAZED PARTITION SYSTEM",
      "totalQty": 192.02,
      "amount": 5405,
    }
  },
];

List purchaseBudgetLabourList = [
  {
    "excelData": {
      "amount": 1346,
      "snNo": "1",
      "specification": "A.1.DEMOLITION WORK",
      "totalQty": 53.82,
      "unit": "SFT"
    },
    "labourDescription": "Civil Works",
    "labourQuantity": 54,
    "labourRate": 25,
    "labourUnit": "SFT",
    "labourAmount": 1346,
  },
  {
    "excelData": {
      "amount": 1615,
      "snNo": "6",
      "specification": "B.7.Leveling mortar",
      "totalQty": 107.64,
      "unit": "SFT"
    },
    "labourDescription": "Civil Works",
    "labourQuantity": 108,
    "labourRate": 15,
    "labourUnit": "SFT",
    "labourAmount": 1615,
  },
  {
    "excelData": {
      "amount": 1,
      "snNo": "7",
      "specification": "B.8.Screed",
      "totalQty": 53.82,
      "unit": "CFT"
    },
    "labourDescription": "Civil Works",
    "labourQuantity": 54,
    "labourRate": 0.01,
    "labourUnit": "CFT",
    "labourAmount": 1,
  },
  {
    "excelData": {
      "amount": 49946,
      "snNo": "9",
      "specification": "C.2.GYPSUM BOARD PARTITION - 100mm Thk",
      "totalQty": 9989.24,
      "unit": "SFT"
    },
    "labourDescription": "Gyp Board",
    "labourQuantity": 10937,
    "labourRate": 5,
    "labourUnit": "SFT",
    "labourAmount": 54682,
  },
  {
    "excelData": {
      "amount": 4736,
      "snNo": "10",
      "specification": "C.3.122mm Drywall",
      "totalQty": 947.26,
      "unit": "SFT"
    },
    "labourDescription": "Gyp Board",
    "labourQuantity": 10937,
    "labourRate": 5,
    "labourUnit": "SFT",
    "labourAmount": 54682,
  },
];

List rateAnalysisList = [
  {
    "id":"1",
    "specification": "A.1.DEMOLITION WORK: Dismantling/removal of existing brick / block wall, existing wall cladding / flooring, door frames and lintels at locations as indicated on the drawings to"
            "accommodate design changes and carƟng away all debris away from site. No additional shall be payable for leads and lifts",
    "boqQty": 5.00,
    "cbQty": 9.29,
    "unit": "Sqm",
    "materialRaQty": 0.00,
    "labourRaQty": 6900.00,
    "matLabRaQty": 6900.00,
    "materialBoqUnit": 0.00,
    "labourBoqUnit": 742.73,
    "matLabBoqUnit": 742.73,
    "materialBoqQty": 0.00,
    "labourBoqQty": 3713.65,
    "matLabBoqQty": 3713.65,
    "pceFinal": 0.00,
    "pceRaQty": 0.00,
    "pceBoqUnit": 0.00,
    "pceBoqQty": 0.00,
    "leadFinal": 0.00,
    "leadRaQty": 0.00,
    "leadBoqUnit": 0.00,
    "leadBoqQty": 0.00,
    "toolsFinal": 0.00,
    "toolsRaQty": 0.00,
    "toolsBoqUnit": 0.00,
    "toolsBoqQty": 0.00,
    "houseFinal": 0.00,
    "houseRaQty": 0.00,
    "houseBoqUnit": 0.00,
    "houseBoqQty": 0.00,
    "totalRaQty": 7452.00,
    "totalBoqUnit": 802.15,
    "totalBoqQty": 4010.76,
    "profitFinal": 39.90,
    "profitRaQty": 2973.35,
    "profitBoqUnit": 320.06,
    "profitBoqQty": 1600.30,
    "msRaQty": 10425.35,
    "msBoqUnit": 1122.21,
    "msBoqQty": 5610.00,
    "materialItems":[],
    "labourItems":[
      {
        "labourDes":"L/w; Demolition; Masnory & Partitions; Upto 150mm thick; 15m Lead; 1 Floor Lift",
        "labourUnit":"SFT",
        "labourQty":100.00,
        "labourRate":25.00,
        "labourAmount":2500.00,
      },
      {
        "labourDes":"L/w; shifting; Any Debris; Down shifting upto location indicated by PM",
        "labourUnit":"CFT",
        "labourQty":150.00,
        "labourRate":15.00,
        "labourAmount":2250.00,
      },
      {
        "labourDes":"L/w; Loading & Disposal; Rubbish; per Truck (100CŌ); Regional vendors",
        "labourUnit":"Nos",
        "labourQty":1.00,
        "labourRate":2150.00,
        "labourAmount":2150.00,
      },
    ],
  },
  {
    "id":"2",
    "specification": "B.1.CIVIL & WETWORKS: CEMENT PLASTERING 19mm: Providing and applying Sand Cement Plaster 1:6 over existing Walls / Columns / RCC Surfaces to line level and plumb to"
  "smooth finish ready receive POP Punning / or cladding. Cost to include for hacking existing surface for proper bonding all complete inclusive of necessary scaffolding & curing."
  "Plastering 12mm average thickness",
    "boqQty": 5.00,
    "cbQty": 9.29,
    "unit": "Sqm",
    "materialRaQty": 2443.00,
    "labourRaQty": 1585.66,
    "matLabRaQty": 4028.66,
    "materialBoqUnit": 262.97,
    "labourBoqUnit": 170.68,
    "matLabBoqUnit": 433.66,
    "materialBoqQty": 1314.85,
    "labourBoqQty": 853.40,
    "matLabBoqQty": 2168.30,
    "pceFinal": 0.00,
    "pceRaQty": 0.00,
    "pceBoqUnit": 0.00,
    "pceBoqQty": 0.00,
    "leadFinal": 0.00,
    "leadRaQty": 0.00,
    "leadBoqUnit": 0.00,
    "leadBoqQty": 0.00,
    "toolsFinal": 0.00,
    "toolsRaQty": 0.00,
    "toolsBoqUnit": 0.00,
    "toolsBoqQty": 0.00,
    "houseFinal": 8.00,
    "houseRaQty": 322.29,
    "houseBoqUnit": 34.69,
    "houseBoqQty": 173.45,
    "totalRaQty": 4350.95,
    "totalBoqUnit": 468.35,
    "totalBoqQty": 2341.74,
    "profitFinal": 11.80,
    "profitRaQty": 513.41,
    "profitBoqUnit": 55.26,
    "profitBoqQty": 276.32,
    "msRaQty": 4864.36,
    "msBoqUnit": 523.61,
    "msBoqQty": 2620.00,
    "materialItems":[
      {
        "materialDes":"S/o; Cement OPC; Grade53; 50kg bags",
        "materialUnit":"Nos",
        "materialQty":1.3,
        "materialRate":310.00,
        "materialAmount":403.00,
      },
      {
        "materialDes":"S/o; Sand; Rough",
        "materialUnit":"CFT",
        "materialQty":12,
        "materialRate":170.00,
        "materialAmount":2040.00,
      },
    ],
    "labourItems":[
      {
        "labourDes":"L/w; Plastering; Rough Finish",
        "labourUnit":"SFT",
        "labourQty":100.00,
        "labourRate":15.00,
        "labourAmount":1500.00,
      },
      {
        "labourDes":"L/w; Shifting; Cement Bag/POP Bag 50KG; Upto Working location",
        "labourUnit":"Nos",
        "labourQty":1.50,
        "labourRate":5.00,
        "labourAmount":7.50,
      },
      {
        "labourDes":"L/w; Shifting; Sand & Course Aggregate; Upto Working location",
        "labourUnit":"CFT",
        "labourQty":9.77,
        "labourRate":8.00,
        "labourAmount":78.16,
      },
    ],
  },
];
